### ISSUE TITLE
Stuck On Loading

### ISSUE THREAD

**Issue by jacksonsp117** [LilSumac/bash-srp-alpha#1]
Got the Gamemode to launch but I remain stuck on "Your session is initializing... Loading..." how do I fix this?

Thank you.

**Comment by LilSumac** [comment]
Hi, sorry for the late reply. Can you supply any console logs/errors to further diagnose this problem?

**Comment by Heyter** [comment]
Project dead?

**Comment by LilSumac** [comment]
Not really, I've just been working on the revamped beta version. If you have any bugs or errors you've encountered, please let me know in a new issue! I'll be closing this one because the OP never followed up with any logs.
